require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']